FROM python:{{python_version}}
MAINTAINER Enrique Garcia Pablos <engapa@gmail.com>

WORKDIR /root

ADD requirements.txt requirements.txt

RUN pip install -U pip
RUN pip install -r requirements.txt
RUN mkdir -p /root/.config/openstack;mkdir -p /etc/openstack

VOLUME ["/root", /root/.config/openstack", "/etc/openstack"]

CMD ["/bin/bash"]
