FROM python:{{python_version}}
MAINTAINER Enrique Garcia Pablos <engapa@gmail.com>

RUN pip install -U pip

{%- for client in clients %}
RUN pip install -U git+https://github.com/openstack/python-{{client}}client@{{release}}#egg=python-{{client}}client
{%- endfor %}
